### Import Relevant packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [18]:
df = pd.read_csv('./dataset.csv')

In [21]:
df['click_through_rates'] = df['click-through-event'] / df['impression']

In [14]:
df_dummies = pd.get_dummies(df['region'])

In [15]:
df_dummies
del df_dummies[df_dummies.columns[-1]]

df_new = pd.concat([df, df_dummies], axis=1)
del df_new['region'] 
del df_new['first_key'] 
del df_new['version'] 
del df_new['season'] 
del df_new['vertical'] 
del df_new['first_dropped'] 
del df_new['impression']

In [16]:
df_new

click-through-event  Africa  Americas  Asia  Europe  Oceania
0                     0.0       0         0     1       0        0
1                  1568.0       0         0     0       0        0
2                     0.0       0         0     0       0        0
3                     0.0       0         0     0       0        0
4                     0.0       0         0     0       0        0
...                   ...     ...       ...   ...     ...      ...
3267               1281.0       1         0     0       0        0
3268                 35.0       1         0     0       0        0
3269               2531.0       0         0     0       1        0
3270                  0.0       0         0     0       1        0
3271                  0.0       0         0     1       0        0

[3272 rows x 6 columns]

In [17]:
x = df_new.values
correlation_matrix = np.corrcoef(x.T)
print(correlation_matrix)

[[ 1.         -0.01141974  0.11383942 -0.02262808  0.0011004  -0.00394138]
 [-0.01141974  1.         -0.06293636 -0.07777894 -0.08349597 -0.00585013]
 [ 0.11383942 -0.06293636  1.         -0.17506941 -0.18793764 -0.01316782]
 [-0.02262808 -0.07777894 -0.17506941  1.         -0.23225988 -0.01627325]
 [ 0.0011004  -0.08349597 -0.18793764 -0.23225988  1.         -0.01746939]
 [-0.00394138 -0.00585013 -0.01316782 -0.01627325 -0.01746939  1.        ]]
